### ISSUE TITLE
Why are init-containers twice for DC ipaas-rest ?

### ISSUE THREAD

**Issue by rhuss** [syndesisio/openshift-templates#34]
Snippet from the DC:

```yaml
  template:
      metadata:
        labels:
          app: redhat-ipaas
          component: ipaas-rest
          deploymentconfig: ipaas-rest
        annotations:
          pod.beta.kubernetes.io/init-containers: |-
            [{
              "name": "openshift-ca-pemtokeystore",
              "image": "${PEMTOKEYSTORE_IMAGE}",
              "imagePullPolicy": "IfNotPresent",
              "args": [
                "-keystore", "/tls-keystore/openshift-truststore.jks",
                "-ca-file", "/var/run/secrets/kubernetes.io/serviceaccount/ca.crt",
                "-ca-file", "/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt",
                "-ca-dir", "/usr/share/ca-certificates/mozilla"
              ],
              "volumeMounts": [{
                "name": "ipaas-rest-tls",
                "mountPath": "/tls-keystore"
              }]
            }]
      spec:
        initContainers:
        - name: openshift-ca-pemtokeystore
          image: ${PEMTOKEYSTORE_IMAGE}
          imagePullPolicy: IfNotPresent
          args:
          - -keystore
          - /tls-keystore/openshift-truststore.jks
          - -ca-file
          - /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          - -ca-file
          - /var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt
          - -ca-dir
          - /usr/share/ca-certificates/mozilla
          volumeMounts:
          - name: ipaas-rest-tls
            mountPath: /tls-keystore
```

Isn't it sufficient to add only one kind of init container (either as annotation or as within the spec) ? // @jimmidyson
